name: Deploy metro-boulot.photos

on:
  push:
    branches:
      - main
    paths:
      - app/front/**

jobs:
  deploy:
    name: Deploy metro-boulot.photos
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'metro-boulot.photos/package-lock.json'
          
      - name: Set up SSH
        uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd
        with:
          ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}
          
      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 167.71.143.97 >> ~/.ssh/known_hosts
          
      - name: Deploy metro-boulot.photos
        run: |
          cd app/front
          npm ci
          npm run build
          npm run deploy
