name: Deploy metro-boulot.photos Config

on:
  push:
    branches:
      - main
    paths:
      - config/**

jobs:
  deploy:
    name: Deploy metro-boulot.photos Config
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd
        with:
          ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 167.71.143.97 >> ~/.ssh/known_hosts

      - name: Deploy Config
        run: |
          cd config
          ./deploy.sh
